rv64i_test_target = \
	add \
	sub \
	sll \
	slt \
	sltu \
	xor \
	srl \
	sra \
	or \
	and \
	addi \
	slli \
	slti \
	sltiu \
	xori \
	andi \
	lui \
	auipc \



rv64i_test_src = $(addsuffix .S, $(rv64i_sc_tests))
