rv64i_test_target = \
	sb \
	sh \
	sw \
	sd \

	# ld \
	# lw \
	# lh \
	# lb \
	# lwu \
	# lbu \
	# lhu \

	# add \
	# sub \
	# sll \
	# slt \
	# sltu \
	# xor \
	# srl \
	# sra \
	# or \
	# and \
	# addi \
	# slli \
	# slti \
	# sltiu \
	# xori \
	# andi \
	# ori \
	# lui \
	# auipc \
	# addiw \
	# slliw \
	# srliw \
	# sraiw \
	# addw \
	# srlw \
	# sllw \
	# subw \
	# sraw \


rv64i_test_src = $(addsuffix .S, $(rv64i_sc_tests))
