rv64um_test_target = \
	$(rv64um_mul) \
	$(rv64um_div) \

rv64um_mul = \
	mul     \
	mulh    \
	mulhsu  \
	mulhu   \
	mulw

rv64um_div = \
	div     \
	divu    \
    divuw   \
    divw    \
    rem     \
    remu    \
    remuw   \
    remw

rv64mi_test_src = $(addsuffix .S, $(rv64um_sc_tests))
