
rv64ui_test_target = \
	$(rv64ui_r_type) \
	$(rv64ui_i_type) \
	$(rv64ui_u_type) \
	$(rv64ui_j_type) \
	$(rv64ui_b_type) \
	$(rv64ui_s_type) \
	$(rv64ui_z_type) \


rv64ui_r_type = \
	add   \
	sub   \
	sll   \
	slt   \
	sltu  \
	xor   \
	srl   \
	sra   \
	or    \
	and   \
	addw  \
	subw  \
	sllw  \
	srlw  \
	sraw  \

rv64ui_i_type = \
	addi  \
	slti  \
	sltiu \
	xori  \
	ori   \
	andi  \
	slli  \
	srli  \
	srai  \
	jalr  \
	lb    \
	lh    \
	lw    \
	lbu   \
	lhu   \
	lwu   \
	ld    \
	addiw \
	slliw \
	srliw \
	sraiw \

rv64ui_u_type = \
	lui   \
	auipc \

rv64ui_j_type = \
	jal   \

rv64ui_b_type = \
	beq   \
	bne   \
	blt   \
	bge   \
	bltu  \
	bgeu  \

rv64ui_s_type = \
	sb    \
	sh    \
	sw    \
	sd    \


rv64ui_test_src = $(addsuffix .S, $(rv64ui_sc_tests))
